dist: trusty
language: go
os:
  - linux

go:
  - 1.12.x

go_import_path: github.com/vladmasarik/bench


script:
- go get -v -t -d ./...
- curl g.co
- go build -o a.out && ./a.out
- go test -bench ${BENCH} -v ./...