dist: trusty
language: go
os: linux

go:
  - 1.12.x

go_import_path: github.com/vladmasarik/bench

script:
- curl g.co
- go build -o a.out && ./a.out
- echo $BENCH
- echo ${BENCH}
- go test -bench ${BENCH} -v ./...